module.exports.Token = require('./token.model');
module.exports.User = require('./user.model');
module.exports.Tank = require('./tank.model');
module.exports.Dispenser = require('./dispenser.model');
module.exports.Nozel = require('./nozel.model');
module.exports.DipChart = require('./dip_chart.model');
module.exports.Supplier = require('./supplier.model');
module.exports.DailyDip = require('./dailydip.model');
module.exports.Dipchart = require('./dipchart.model');
module.exports.Carriage = require('./carriage.model');
module.exports.Salesman = require('./salesman.model');
module.exports.Customer = require('./customer.model');
module.exports.Employee = require('./employee.model');
module.exports.Product = require('./product.model');
module.exports.FuelPurchase = require('./fuel_purchase.model');
module.exports.OtherPurchase = require('./other_purchase.model');
module.exports.OtherSale = require('./other_sale.model');
module.exports.FuelSale = require('./fuel_sale.model');
module.exports.Roles = require('./role.model');
module.exports.Shift = require('./shift.model');
module.exports.sale_return=require("./sale_return.model")
module.exports.expire_brkge=require("./expire_brkge.model")